/**
 * Properties emitted by the official Joplin core serializer for a newly
 * parsed item with omitted values. The server parses an uploaded item and
 * serializes it again on reads, so create actions must include these values
 * to make journal readback deterministic.
 *
 * Provenance: @joplin/lib@3.7.1, JoplinDatabase schema v53, generated by
 * research/core-feasibility/codec-proof.cjs. Timestamp fields are supplied by
 * the caller as ISO strings; todo_due/todo_completed are integer millisecond
 * strings because BaseItem.serialize_format does not date-format those fields.
 */
const defaults = {
  1: {
    is_conflict: '0', latitude: '0.00000000', longitude: '0.00000000', altitude: '0.0000', author: '', source_url: '',
    is_todo: '0', todo_due: '0', todo_completed: '0', source: '', source_application: '', application_data: '', order: '0',
    encryption_cipher_text: '', encryption_applied: '0', markup_language: '0', is_shared: '0', share_id: '',
    conflict_original_id: '', master_key_id: '', user_data: '', deleted_time: '0', is_locked: '0', extracted_resource_ids: '',
  },
  2: {
    encryption_cipher_text: '', encryption_applied: '0', is_shared: '0', share_id: '', master_key_id: '', icon: '',
    user_data: '', deleted_time: '0',
  },
  5: {
    encryption_cipher_text: '', encryption_applied: '0', is_shared: '0', parent_id: '', user_data: '',
  },
  6: {
    encryption_cipher_text: '', encryption_applied: '0', is_shared: '0',
  },
} as const;

export type CanonicalItemType = keyof typeof defaults;

export function canonicalItemProperties(type: CanonicalItemType, now: string, overrides: Record<string, string> = {}): Record<string, string> {
  const timestamps = { created_time: now, updated_time: now, user_created_time: now, user_updated_time: now };
  const properties: Record<string, string> = { ...timestamps, ...defaults[type], ...overrides };
  // Joplin core parses blank numeric fields as zero before reserializing an
  // uploaded record. Mirror that conversion so strict write readback remains
  // stable for records created by older clients.
  for (const [key, defaultValue] of Object.entries(defaults[type])) {
    if (defaultValue !== '' && properties[key] === '') properties[key] = defaultValue;
  }
  return properties;
}
